server:
  port: 8104
  servlet:
    context-path: /api

accounts:
  allow-active: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka